# Generated by Django 4.2.2 on 2023-06-06 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=50, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=150, null=True, verbose_name='Endereço')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('data_pub', models.DateField(verbose_name='Data de Publicação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('atividade', models.CharField(max_length=300, verbose_name='Atividade')),
                ('salario', models.CharField(max_length=50, verbose_name='Salário')),
                ('horarios', models.CharField(max_length=10, verbose_name='Horários')),
                ('total_vagas', models.CharField(max_length=50, verbose_name='Total de Vagas')),
                ('curriulos', models.CharField(max_length=250, verbose_name='Curriculos')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vagas', to='vagas.empresa')),
                ('cpf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_vagas', to='vagas.cliente')),
            ],
        ),
    ]
