# Generated by Django 4.2.2 on 2023-06-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='cnpj',
        ),
    ]
