# Generated by Django 4.2.2 on 2023-06-06 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_remove_vaga_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='cpf',
        ),
        migrations.AddField(
            model_name='vaga',
            name='cnpj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='empresa_vagas', to='vagas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vaga',
            name='horarios',
            field=models.CharField(max_length=50, verbose_name='Horários'),
        ),
    ]
